export { default as Form } from './Form'
export { default as HeadCard } from './HeadCard'
export { default as MultipleChoice } from './MultipleChoice'
export { default as NameInput } from './NameInput'
export { default as ShortText } from './ShortText'
export { default as Submit } from './Submit'
export { default as Letter } from './Letter'
export { default as MusicPlayer} from './MusicPlayer'